### ISSUE TITLE
Question on packages used

### ISSUE THREAD

**Issue by pieterlouw** [knq/sdhook#10]
Hi,
I see the current Stackdriver docs reference `cloud.google.com/go/logging` and `cloud.google.com/go/errorreporting` as the client library packages to use when you want to call Stackdriver from your Go app, however I see the code use different packages(`google.golang.org/api/clouderrorreporting/v1beta1` and
`google.golang.org/api/logging/v2`)

Is there a specific reason for this?

Pieter

**Comment by kenshaw** [comment]
I just looked at the source for this package, and I do not see any packages imported from the `cloud.google.com/go/*` namespace, other than the `metadata` package, which is used / needed for retreiving the scopes from the GCP metadata service. Could you clarify what you're referring to?

**Comment by pieterlouw** [comment]
Hi @kenshaw ,
Sorry for not being clear. 

https://github.com/knq/sdhook/blob/master/sdhook.go references the following packages: 
``` go
errorReporting "google.golang.org/api/clouderrorreporting/v1beta1"
logging "google.golang.org/api/logging/v2"
```

My question is if there's a specific reason why these packages are used and not the packages from the `cloud.google.com/go/*` namespace? It seems the `cloud.google.com/go/*` are the preferred packages to use as they are the one's used in the official docs. 

Pieter
