### ISSUE TITLE
New Trace log level in logrus

### ISSUE THREAD

**Issue by dgsb** [knq/sdhook#18]
Hello, I'm just opening this issue to let you know, the next release of logrus (v1.2.0) will add a new trace level named Trace below Debug.
Here is the PR for reference sirupsen/logrus#844
You may want to take into account this new level.

**Comment by kenshaw** [comment]
Appreciate the heads up, I'm not sure if this is relevant to this hook, as StackDriver doesn't have a trace level. It should be treated the same as any other logging entry.
